#!/usr/bin/perl
#
# provide some standard aliases for commands for terminally
# helpless ak1a user (helpless in the sense that they never
# read nor understand help files)
#
# This file is automagically reloaded if its modification time is 
# later than the one stored in CmdAlias.pm
#
# PLEASE make this file consistant with reality! (the patterns MUST
# match the filenames!)
#
# Don't alter this file, copy it into the local_cmd tree and modify it.
# This file will be replaced everytime I issue a new release.
#
# You only need to put aliases in here for commands that don't work as
# you desire naturally, e.g sh/dx on its own just works as you expect
# so you need not add it as an alias.
#


package CmdAlias;

%alias = (
    '?' => [
	  '^\?', 'apropos', 'apropos',
	],
    'a' => [
	'^acc?e?p?t?$', 'apropos accept', 'apropos',
	  '^ann\w*/full', 'announce full', 'announce', 
	  '^ann\w*/sysop', 'announce sysop', 'announce',
	  '^ann\w*/(.*)$', 'announce $1', 'announce',
	],
	'b' => [
	  '^b$', 'bye', 'bye',
	],
	'c' => [
	'^cle?a?r?$', 'apropos clear', 'apropos',
	'^cre?a?t?e?$', 'apropos create', 'apropos',
	],
	'd' => [
	'^dele?t?e?$', 'apropos delete', 'apropos',
	  '^del\w*/u', 'delete/user', 'delete/user',
	  '^del\w*/fu', 'kill full', 'kill',
	  '^del', 'kill', 'kill',
	  '^di\w*/a\w*', 'directory all', 'directory',
	  '^di\w*/b\w*', 'directory bulletins', 'directory',
	  '^di\w*/n\w*', 'directory new', 'directory',
	  '^di\w*/o\w*', 'directory own', 'directory',
	  '^di\w*/s\w*', 'directory subject', 'directory',
	  '^di\w*/t\w*', 'directory to', 'directory',
	  '^di\w*/f\w*', 'directory from', 'directory',
	  '^di\w*/(\d+)-(\d+)', 'directory $1-$2', 'directory',
	  '^di\w*/(\d+)', 'directory $1', 'directory',
	],
	'e' => [
	  '^exi?t?$', 'bye', 'bye',
	  '^exp?u?\w+$', 'kill expunge', 'kill expunge',
	],
	'f' => [
	'^fo\w*$', 'apropos forward', 'apropos',
	],
	'g' => [
	],
	'h' => [
	],
	'i' => [
	],
	'j' => [
	],
	'k' => [
	],
	'l' => [
	'^loa?d?$', 'apropos load', 'apropos',
	  '^l$', 'directory', 'directory',
	  '^ll$', 'directory', 'directory',
	  '^ll/(\d+)', 'directory $1', 'directory',
	  '^lm$', 'directory own', 'directory',
	],
	'm' => [
	],
	'n' => [
	],
	'o' => [
	],
	'p' => [
	],
	'q' => [
	  '^q', 'bye', 'bye',
	],
	'r' => [	
	'^reje?c?t?$', 'apropos reject', 'apropos',
	  '^r$', 'read', 'read',
	  '^rcmd/(\S+)', 'rcmd $1', 'rcmd',
	],
	's' => [
	  '^s/p$', 'send', 'send',
	  '^sb$', 'send noprivate', 'send',
	  '^set/home$', 'set/homenode', 'set/homenode',
	  '^set/nobe', 'unset/beep', 'unset/beep',
	  '^set/nohe', 'unset/here', 'unset/here',
	  '^set/noan', 'unset/announce', 'unset/announce',
	  '^set/nodxg', 'unset/dxgrid', 'unset/dxgrid',
	  '^set/nodx', 'unset/dx', 'unset/dx',
	  '^set/noe', 'unset/echo', 'unset/echo',
	  '^set/nota', 'unset/talk', 'unset/talk',
	  '^set/noww', 'unset/wwv', 'unset/wwv',
	  '^set/nowx', 'unset/wx', 'unset/wx',
	'^set$', 'apropos set', 'apropos',
	  '^sho?w?/u$', 'show/user', 'show/user',
	  '^sho?w?/bu', 'show/files bulletins', 'show/files',
	  '^sho?w?/c/n', 'show/configuration nodes', 'show/configuration',
	  '^sho?w?/c$', 'show/configuration', 'show/configuration',
	  '^sho?w?/com', 'dbavail', 'dbavail',
	  '^sho?w?/dx/(\d+)-(\d+)', 'show/dx $1-$2', 'show/dx',
	  '^sho?w?/dx/(\d+)', 'show/dx $1', 'show/dx',
	  '^sho?w?/dx/d(\d+)', 'show/dx from $1', 'show/dx',
	  '^sho?w?/newc/n', 'show/newconfiguration node', 'show/newconfiguration',
	  '^sho?w?/tnc', 'who', 'who',
      '^sho?w?/up', 'show/cluster', 'show/cluster',
	  '^sho?w?/ww?v?/(\d+)-(\d+)', 'show/wwv $1-$2', 'show/wwv',
	  '^sho?w?/ww?v?/(\d+)', 'show/wwv $1', 'show/wwv',
	'^shut?d?\w*$', 'shutdown', 'shutdown',
	'^sho?w?$', 'apropos show', 'apropos',
	  '^sp$', 'send', 'send',
	'^sta?t?$', 'apropos stat', 'apropos',
      	
    ],
	't' => [
	  '^ta$', 'talk', 'talk',
	  '^t$', 'talk', 'talk',
	],
	'u' => [
	'^uns?e?t?$', 'apropos unset', 'apropos',
	],
	'v' => [
	],
	'w' => [
	  '^wx/full', 'wx full', 'wx',
	  '^wx/sysop', 'wx sysop', 'wx',
	],
	'x' => [
	],
	'y' => [
	],
	'z' => [
	],
)
