#!/usr/bin/perl
# 
# this file contains the system messages. Don't forget to reload them
# if you change them (load/messages)
#
# $Id$
#

package DXM;

%msgs = (
		 en => {
				addr => 'Address set to: $_[0]',
                already => '$_[0] already connnected',
				anns => 'Announce flag set on $_[0]',
				annu => 'Announce flag unset on $_[0]',
				conother => 'Sorry $_[0] you are connected on another port',
				concluster => 'Sorry $_[0] you are already connected elsewhere on the cluster',
				confail => 'connection to $_[0] failed ($_[1])',
				constart => 'connection to $_[0] started',
				dx1 => 'Frequency $_[0] not in band [usage: DX freq call comments](see sh/band)',
				dx2 => 'Need a callsign [usage: DX freq call comments]',
				dxs => 'DX Spots flag set on $_[0]',
				dxu => 'DX Spots flag unset on $_[0]',
				e1 => 'Invalid command',
				e2 => 'Error: $_[0]',
				e3 => '$_[0]: $_[1] not found',
				e4 => 'Need at least a prefix or callsign',
				e5 => 'Not Allowed',
				e6 => 'Need a callsign',
				e7 => 'callsign $_[0] not visible on the cluster',
				email => 'E-mail address set to: $_[0]',
				heres => 'Here set on $_[0]',
				hereu => 'Here unset on $_[0]',
				homebbs => 'Home BBS set to: $_[0]',
				homenode => 'Home Node set to: $_[0]',
				l1 => 'Sorry $_[0], you are already logged on on another channel',
				l2 => 'Hello $_[0], this is $main::mycall in $main::myqth running DXSpider V$main::version',
				m2 => '$_[0] Information: $_[1]',
				node => '$_[0] set as AK1A style Node',
				nodec => '$_[0] created as AK1A style Node',
				nodee1 => 'You cannot use this command whilst your target ($_[0]) is on-line',
				ok => 'Operation successful',
				page => 'Press Enter to continue, A to abort ($_[0] lines) >',
				pingo => 'Ping Started to $_[0]',
				pingi => 'Ping Returned from $_[0] ($_[2] secs)',
				pr => '$_[0] de $main::mycall $main::cldate $main::ztime >',
				priv => 'Privilege level changed on $_[0]',
				prx => '$main::mycall >',
				rcmdo => 'RCMD \"$_[0]\" sent to $_[1]',
				read1 => 'Sorry, no new messages for you',
				read2 => 'Msg $_[0] not found',
				read3 => 'Msg $_[0] not available',
				shutting => '$main::mycall shutting down...',
				talks => 'Talk flag set on $_[0]',
				talku => 'Talk flag unset on $_[0]',
				wwvs => 'WWV flag set on $_[0]',
				wwvu => 'WWV flag unset on $_[0]',
		},
  fr => {
		},
  de => {
		},
);
